### PR TITLE
Fixes maven sources warning

### LINKED ISSUE #310: Warning about using deprecated maven goal `sources'
Since the update to Ubuntu 24.04 ([and thus maven 3.9.9](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md#project-management)) tests fail with:

```
Error:  Failures: 
Error:    DebugSymbolsTest.debugSymbolsQuarkus:290 build-and-run.log log should not contain error or warning lines that are not whitelisted. See /home/runner/work/mandrel/mandrel/mandrel-integration-tests/testsuite/target/archived-logs/org.graalvm.tests.integration.DebugSymbolsTest/debugSymbolsQuarkus/build-and-run.log and check these offending lines: 
Warning:   Goal 'sources' is deprecated: in favor of resolve-sources goal and will be removed in a future version ==> expected: <true> but was: <false>
```

### PR DESCRIPTION
**Pull request by Karm**
fixes #310

### CODE REVIEW

**Review by jerboaa — APPROVED** [review]

**Review by zakkak — COMMENTED** [review]
LGTM but the CI fails with:

```
Error:  Failures: 
Error:    DebugSymbolsTest.debugSymbolsQuarkus:290 build-and-run.log log should not contain error or warning lines that are not whitelisted. See /home/runner/work/mandrel-integration-tests/mandrel-integration-tests/ts/testsuite/target/archived-logs/org.graalvm.tests.integration.DebugSymbolsTest/debugSymbolsQuarkus/build-and-run.log and check these offending lines: 
[INFO] Can't extract module name from quarkus-rest-client-3.9.5-sources.jar: Provider class io.quarkus.rest.client.reactive.runtime.spi.JsonMissingMessageBodyReaderErrorMessageContextualizer not in JAR file quarkus-rest-client-3.9.5-sources.jar ==> expected: <true> but was: <false>
```

Which I have never seen before.

File: testsuite/src/it/java/org/graalvm/tests/integration/utils/WhitelistLogLines.java [hunk 1]
```diff
@@ -171,6 +171,8 @@ public Pattern[] get(boolean inContainer) {
                     Pattern.compile(".*WARNING: sun.misc.Unsafe::arrayBaseOffset has been called by .*jctools.util.UnsafeRefArrayAccess.*"),
                     Pattern.compile(".*WARNING: Please consider reporting this to the maintainers of class .*jctools.util.UnsafeRefArrayAccess"),
                     Pattern.compile(".*WARNING: sun.misc.Unsafe::arrayBaseOffset will be removed in a future release"),
+                    // Ignore INFO message about class containing Error in its name
+                    Pattern.compile(".*\\[INFO\\] Can't extract module name from .*JsonMissingMessageBodyReaderErrorMessageContextualizer.*"),
```
Comment (zakkak) [inline testsuite/src/it/java/org/graalvm/tests/integration/utils/WhitelistLogLines.java:175]: @Karm FYI ^^
